version: "3.8"

services:
    limbless-server:
        container_name: limbless-web-server
        build:
            context: ./services/limbless-server
            dockerfile: Dockerfile.dev
        command: "flask run --host=0.0.0.0"
        volumes:
            - ./services/limbless-server/limbless:/usr/src/app/limbless
            - ./uploads:/usr/src/app/uploads
            - ./logs/limbless:/usr/src/app/logs
            - ./data:/usr/src/app/data:ro
            - ./services/limbless-server/static/style:/usr/src/app/static/style
        env_file: .dev.env
        ports:
            - 5000:5000
        expose:
            - 5000
        depends_on:
            postgres:
                condition: service_healthy
                restart: true

        healthcheck:
            test: ["CMD", "curl", "-f", "http://limbless-server:5000/status"]
            interval: 10s
            timeout: 10s
            retries: 5

    postgres:
        container_name: limbless-postgres-db
        image: postgres:16rc1-alpine3.17
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        restart: always
        volumes:
            - ./db/postgres:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
            interval: 10s
            timeout: 10s
            retries: 5

    pgadmin:
        container_name: limbless-pgadmin
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        ports:
            - 5050:80
        restart: always
        volumes:
            - ./db/pgadmin:/var/lib/pgadmin
        depends_on:
            postgres:
                condition: service_healthy
                restart: true