services:
    limbless-app:
        container_name: limbless-app-dev
        build:
            context: ./services/limbless-app
            dockerfile: Dockerfile.dev
        volumes:
            - ./services/limbless-app/limbless-server:/usr/src/app/limbless-server
            - ./services/limbless-app/limbless-db:/usr/src/app/limbless-db
            - ./services/limbless-app/static/images:/usr/src/app/static/images:ro
            - ./services/limbless-app/static/js:/usr/src/app/static/js:ro
            - ./services/limbless-app/static/resources:/usr/src/app/static/resources:ro
            - ./services/limbless-app/templates:/usr/src/app/templates:ro
            - ./cert:/usr/src/app/cert
            - ${UPLOADS_DIR}:/usr/src/app/uploads
            - ${DATA_DIR}/media:/usr/src/app/media
            - ${DATA_DIR}/logs/limbless:/usr/src/app/logs
            - ${DB_DIR}/dev_init:/usr/src/app/init
            - compiled_css:/usr/src/app/static/style/compiled:ro
        environment:
            TZ: ${TIMEZONE}
        env_file: .env
        ports:
            - ${LIMBLESS_PORT}:${LIMBLESS_PORT}
        expose:
            - ${LIMBLESS_PORT}
        restart: always
        depends_on:
            postgres:
                condition: service_healthy
                restart: true
            sass-compiler:
                condition: service_started
                restart: true
            redis-cache:
                condition: service_healthy
                restart: true
        healthcheck:
            test: ["CMD", "curl", "-f", "http://limbless-app:${LIMBLESS_PORT}/status"]
            interval: 60s
            timeout: 10s
            retries: 5

    rf-scanner:
        container_name: rf-scanner-dev
        build:
            context: ./services
            dockerfile: rf-scanner/Dockerfile
            args:
                RUN_FOLDER_SCAN_INTERVAL_MINS: ${RUN_FOLDER_SCAN_INTERVAL_MINS}
        env_file: .env
        environment:
            TZ: ${TIMEZONE}
        volumes:
            - ./services/rf-scanner/src:/usr/src/app/src:ro
            - ${DATA_DIR}/logs/rf-scanner:/var/log
            - ${ILLUMINA_RUN_FOLDER}:/illumina_run_folder
        depends_on:
            postgres:
                condition: service_healthy
                restart: true
        restart: always
        
    redis-cache:
        container_name: redis-cache-dev
        image: redis:6.2-alpine
        environment:
            - TZ=${TIMEZONE}
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}
        restart: always
        volumes:
            - ./cache:/data
        healthcheck:
            test: ["CMD", "redis-cli", "-p", "${REDIS_PORT}", "ping"]
            interval: 10s
            timeout: 10s
            retries: 5
        command: --port ${REDIS_PORT}

    sass-compiler:
        container_name: sass-compiler-dev
        build: ./services/sass-compiler
        volumes:
            - ./services/limbless-app/static/style/sass:/usr/src/app/static/style/sass:ro
            - compiled_css:/usr/src/app/static/style/compiled
        command: "sass --watch /usr/src/app/static/style/sass:/usr/src/app/static/style/compiled"
        environment:
            - TZ=${TIMEZONE}
        healthcheck:
            test: ["CMD-SHELL", "ps cax | grep -wq sass"]
            interval: 10s
            timeout: 10s
            retries: 5

    postgres:
        container_name: postgres-dev
        image: postgres:16rc1-alpine3.17
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            PGPORT: ${POSTGRES_PORT}
            TZ: ${TIMEZONE}
        expose:
            - ${POSTGRES_PORT}
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        restart: always
        volumes:
            - ./templates/postgres/postgresql.conf:/etc/postgresql.conf
            - ${DB_DIR}/dev_postgres:/var/lib/postgresql/data
            - ${DATA_DIR}/db_backup/wal:/var/lib/postgresql/backup
        healthcheck:
            test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
            interval: 10s
            timeout: 10s
            retries: 5
        command: "postgres -c config_file=/etc/postgresql.conf"

    pgadmin:
        container_name: pgadmin-dev
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
            TZ: ${TIMEZONE}
        ports:
            - ${PGADMIN_PORT}:80
        restart: always
        volumes:
            - ${DB_DIR}/dev_pgadmin:/var/lib/pgadmin
        depends_on:
            postgres:
                condition: service_healthy
                restart: true
        attach: false  # no logs

    yacht:
        container_name: yacht-dev
        environment:
            TZ: ${TIMEZONE}
        image: selfhostedpro/yacht:latest
        ports:
            - ${YACHT_PORT}:8000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - yacht:/config
        restart: always

volumes:
    compiled_css:
    yacht: