services:
    limbless-pytest:
        container_name: limbless-pytest
        build:
            context: ./services
            dockerfile: pytest/Dockerfile
        command: "pytest tests/ -s"
        volumes:
            - ./services/pytest/tests:/usr/src/app/tests:ro
            - ./services/limbless-app/static/resources/templates/library_prep/:/usr/src/app/prep_tables:ro
            - ./services/limbless-app/limbless-db:/usr/src/app/limbless-db:ro
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: test_db
            POSTGRES_PORT: 5434
            POSTGRES_HOST: postgres
            TIMEZONE: "Europe/Vienna"
            TZ: "Europe/Vienna"
        depends_on:
            postgres:
                condition: service_healthy
                restart: true

    postgres:
        container_name: limbless-postgres-db-test
        image: postgres:16rc1-alpine3.17
        command: "-c logging_collector=on"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: test_db
            PGPORT: 5434
            TZ: "Europe/Vienna"
        expose:
            - 5434
        ports:
            - 5434:5434
        healthcheck:
            test: ["CMD", "pg_isready", "-d", "test_db", "-U", "admin"]
            interval: 10s
            timeout: 10s
            retries: 5