services:
    opengsync-pytest:
        container_name: opengsync-pytest
        build:
            context: ./services
            dockerfile: pytest/Dockerfile
        command: "pytest tests/ -s"
        volumes:
            - ./services/pytest/tests:/usr/src/app/tests:ro
            - ./services/opengsync-app/static/resources/templates/library_prep/:/usr/src/app/prep_tables:ro
            - ./services/opengsync-app/opengsync-db:/usr/src/app/opengsync-db:ro
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: test_db
            POSTGRES_PORT: 5434
            POSTGRES_HOST: postgres
            LAB_PROTOCOL_START_NUMBER: 0
            TIMEZONE: "Europe/Vienna"
            TZ: "Europe/Vienna"
        depends_on:
            postgres:
                condition: service_healthy
                restart: true

    postgres:
        container_name: opengsync-postgres-db-test
        image: postgres:17.5-alpine3.22
        command: "-c logging_collector=on"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: test_db
            PGPORT: 5434
            TZ: "Europe/Vienna"
        expose:
            - 5434
        ports:
            - 5434:5434
        healthcheck:
            test: ["CMD", "pg_isready", "-d", "test_db", "-U", "admin"]
            interval: 10s
            timeout: 10s
            retries: 5